services:
  - type: web
    name: best-mimic-wins
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
